POST http://localhost:3000/api/wilder/create HTTP/1.1
content-type: application/json

{
    "name": "Http wilder 62",
    "city": "Londres",
    "skills": [
        { "title": "express", "votes": 5 },
        { "title": "mongo", "votes": 12 }
    ]
}

####

GET http://localhost:3000/api/wilder/read HTTP/1.1
content-type: application/json

###

POST http://localhost:3000/api/wilder/update HTTP/1.1
content-type: application/json

{
    "name": "Wilder two",
    "newName": "wilder 2"
}

###
DELETE http://localhost:3000/api/wilder/delete HTTP/1.1
content-type: application/json

{
    "name": "new name"
}